const settingsModule={async renderSettings(el){
  const get=async k=>(await db.settings.get(k))?.value||'';
  const [commission,subEnd,match,theme,freeLimit]=await Promise.all([get('commissionRate'),get('subscriptionEnd'),get('matchingWeights'),get('theme'),get('freeUserLimit')]);
  const current=theme||localStorage.getItem('melkyar_theme')||'light';
  el.innerHTML=mk.page('تنظیمات','تنظیمات برنامه، ظاهر، کاربران و اطلاعات سازنده','')+`<section class="panel"><h3>تم رابط کاربری</h3><div class="theme-grid">${[['light','روشن'],['dark','تیره'],['emerald-gold','سبز و طلایی'],['sage','سبز ملایم'],['sand','کرم و طلایی']].map(([k,l])=>`<button type="button" class="theme-option ${current===k?'active':''}" data-theme="${k}">${l}</button>`).join('')}</div></section>
  <section class="panel"><h3>تنظیمات مالی و هوشمند</h3><div class="form-grid">${mk.input('درصد پیش‌فرض کمیسیون','commissionRate',commission||'1.5','number')}${mk.input('تاریخ پایان اشتراک','subscriptionEnd',subEnd,'date')}${mk.input('وزن‌های تطبیق (JSON)','matchingWeights',match||'{"area":25,"budget":30,"bedrooms":20,"amenities":25}')}${mk.input('حد رایگان کاربران','freeUserLimit',freeLimit||'3','number')}</div><button class="btn btn--primary" id="save-settings">ذخیره تنظیمات</button></section>
  <section class="panel"><div class="page-header"><div><h3>کاربران و دسترسی‌ها</h3><p class="muted">سه کاربر اول رایگان؛ کاربر چهارم به بعد نیازمند تأیید سازنده است.</p></div></div><div id="embedded-users"></div></section>
  <section class="panel"><h3>مدیریت سازنده</h3><p>حساب سازنده: <strong>alireza</strong> — درخواست‌های کاربر جدید از همین بخش بررسی و تأیید می‌شوند.</p></section><section class="panel"><h3>اطلاعات سازنده</h3><p>طراحی و ساخت توسط <strong>علیرضا بدر</strong></p><p>شرکت برنامه نویسی قو (سهامی خاص) — علیرضا بدر (Swanco)</p></section>`;
  el.querySelectorAll('[data-theme]').forEach(b=>b.onclick=async()=>{const t=b.dataset.theme;document.documentElement.setAttribute('data-theme',t);localStorage.setItem('melkyar_theme',t);for(const x of el.querySelectorAll('[data-theme]'))x.classList.toggle('active',x===b);const old=await db.settings.get('theme');old?await db.settings.update('theme',{value:t}):await db.settings.add({key:'theme',value:t});});
  el.querySelector('#save-settings').onclick=async()=>{for(const k of ['commissionRate','subscriptionEnd','matchingWeights','freeUserLimit']){const v=el.querySelector(`[name="${k}"]`).value;const old=await db.settings.get(k);old?await db.settings.update(k,{value:v}):await db.settings.add({key:k,value:v});}ui.toast('تنظیمات ذخیره شد','success');};
  if(window.usersModule) await usersModule.renderUsers(el.querySelector('#embedded-users'),true);
}};window.settingsModule=settingsModule;